group=cool.azu.sample
version=1.0.0

# Sets the Minecraft version to use with the 'runServer' task.
serverVersion=1.21.3

# Sets the plugin name, description and website.
# The description and website are both optional and can be commented out.
pluginName=SamplePlugin
pluginDescription=It's as shrimple as that
pluginWebsite=https://azu.cool